from __future__ import annotations

from src.executive.models import ExecutiveActionDefinition, ExecutiveComponent


ACTION_DEFINITIONS: dict[str, ExecutiveActionDefinition] = {
    "recheck_component": ExecutiveActionDefinition(
        action_id="recheck_component",
        label="Recheck Component",
        description="Refresh live health information for one component.",
        component_scope=["*"],
        risk_level="low",
        requires_confirmation=False,
    ),
    "collect_component_diagnostics": ExecutiveActionDefinition(
        action_id="collect_component_diagnostics",
        label="Collect Diagnostics",
        description="Gather a structured diagnostic snapshot for a component.",
        component_scope=["*"],
        risk_level="low",
        requires_confirmation=False,
    ),
    "tail_component_logs": ExecutiveActionDefinition(
        action_id="tail_component_logs",
        label="Tail Logs",
        description="Read the latest relevant lines for a component log.",
        component_scope=["frontend", "gateway", "langgraph", "nginx", "litellm", "langfuse", "surfsense"],
        risk_level="low",
        requires_confirmation=False,
        input_schema={"lines": {"type": "integer", "minimum": 10, "maximum": 200}},
    ),
    "run_connectivity_check": ExecutiveActionDefinition(
        action_id="run_connectivity_check",
        label="Run Connectivity Check",
        description="Perform a direct connectivity probe against a component endpoint.",
        component_scope=["frontend", "gateway", "langgraph", "nginx", "litellm", "langfuse", "surfsense"],
        risk_level="low",
        requires_confirmation=False,
    ),
    "refresh_mcp": ExecutiveActionDefinition(
        action_id="refresh_mcp",
        label="Refresh MCP",
        description="Reload extensions config and reset the MCP tool cache.",
        component_scope=["mcp"],
        risk_level="low",
        requires_confirmation=False,
    ),
    "enable_mcp_server": ExecutiveActionDefinition(
        action_id="enable_mcp_server",
        label="Enable MCP Server",
        description="Enable a configured MCP server in extensions config.",
        component_scope=["mcp"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"server_name": {"type": "string"}},
    ),
    "disable_mcp_server": ExecutiveActionDefinition(
        action_id="disable_mcp_server",
        label="Disable MCP Server",
        description="Disable a configured MCP server in extensions config.",
        component_scope=["mcp"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"server_name": {"type": "string"}},
    ),
    "restart_channel": ExecutiveActionDefinition(
        action_id="restart_channel",
        label="Restart Channel",
        description="Restart one configured IM channel.",
        component_scope=["channels"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"channel_name": {"type": "string"}},
    ),
    "sync_context_packs": ExecutiveActionDefinition(
        action_id="sync_context_packs",
        label="Sync Context Packs",
        description="Refresh OpenViking context packs and recent cache metadata.",
        component_scope=["openviking"],
        risk_level="low",
        requires_confirmation=False,
    ),
    "run_approved_flow": ExecutiveActionDefinition(
        action_id="run_approved_flow",
        label="Run Approved Flow",
        description="Trigger one approved Activepieces flow through the MaestroFlow bridge.",
        component_scope=["activepieces"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"flow_id": {"type": "string"}, "input": {"type": "object"}},
    ),
    "create_browser_job": ExecutiveActionDefinition(
        action_id="create_browser_job",
        label="Create Browser Job",
        description="Run a browser extraction or navigation job through the runtime bridge.",
        component_scope=["browser_runtime"],
        risk_level="low",
        requires_confirmation=False,
        input_schema={"action": {"type": "string"}, "url": {"type": "string"}, "runtime": {"type": "string"}},
    ),
    "create_state_snapshot": ExecutiveActionDefinition(
        action_id="create_state_snapshot",
        label="Create State Snapshot",
        description="Capture a state snapshot for a thread, project, experiment, or workflow run.",
        component_scope=["stateweave"],
        risk_level="low",
        requires_confirmation=False,
        input_schema={
            "target_kind": {"type": "string"},
            "target_id": {"type": "string"},
            "label": {"type": "string"},
            "payload": {"type": "object"},
        },
    ),
    "update_subagent_timeout": ExecutiveActionDefinition(
        action_id="update_subagent_timeout",
        label="Update Subagent Timeout",
        description="Apply a runtime timeout override for subagents.",
        component_scope=["subagents"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={
            "timeout_seconds": {"type": "integer", "minimum": 60, "maximum": 7200},
            "agent_name": {"type": "string"},
        },
    ),
    "update_subagent_concurrency_policy": ExecutiveActionDefinition(
        action_id="update_subagent_concurrency_policy",
        label="Update Subagent Concurrency",
        description="Apply a runtime concurrency override for the lead agent's subagent fan-out.",
        component_scope=["subagents"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"max_concurrent_subagents": {"type": "integer", "minimum": 1, "maximum": 4}},
    ),
    "set_default_model": ExecutiveActionDefinition(
        action_id="set_default_model",
        label="Set Default Model",
        description="Apply a runtime default model override for MaestroFlow agents.",
        component_scope=["lead_agent"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"model_name": {"type": "string"}},
    ),
    "cancel_doc_edit_run": ExecutiveActionDefinition(
        action_id="cancel_doc_edit_run",
        label="Cancel Doc Edit Run",
        description="Mark an awaiting-selection doc edit run as cancelled.",
        component_scope=["doc_editing"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"run_id": {"type": "string"}},
    ),
    "retry_doc_edit_run": ExecutiveActionDefinition(
        action_id="retry_doc_edit_run",
        label="Retry Doc Edit Run",
        description="Create a fresh doc edit run from a previous run's manifest.",
        component_scope=["doc_editing"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"run_id": {"type": "string"}},
    ),
    "approve_autoresearch_experiment": ExecutiveActionDefinition(
        action_id="approve_autoresearch_experiment",
        label="Approve Experiment",
        description="Promote a qualified Autoresearch experiment winner into the live prompt registry.",
        component_scope=["autoresearch"],
        risk_level="high",
        requires_confirmation=True,
        input_schema={"experiment_id": {"type": "string"}},
    ),
    "reject_autoresearch_experiment": ExecutiveActionDefinition(
        action_id="reject_autoresearch_experiment",
        label="Reject Experiment",
        description="Reject a pending Autoresearch promotion candidate.",
        component_scope=["autoresearch"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"experiment_id": {"type": "string"}, "reason": {"type": "string"}},
    ),
    "rollback_autoresearch_prompt": ExecutiveActionDefinition(
        action_id="rollback_autoresearch_prompt",
        label="Rollback Prompt",
        description="Replace a role's champion prompt with a previous or manual prompt revision.",
        component_scope=["autoresearch"],
        risk_level="high",
        requires_confirmation=True,
        input_schema={"role": {"type": "string"}, "prompt_text": {"type": "string"}},
    ),
    "stop_autoresearch_experiment": ExecutiveActionDefinition(
        action_id="stop_autoresearch_experiment",
        label="Stop Experiment",
        description="Stop a running or pending Autoresearch experiment.",
        component_scope=["autoresearch"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"experiment_id": {"type": "string"}, "reason": {"type": "string"}},
    ),
    "sync_openviking_context_packs": ExecutiveActionDefinition(
        action_id="sync_openviking_context_packs",
        label="Sync Context Packs",
        description="Upsert one or more context packs into the OpenViking registry.",
        component_scope=["openviking"],
        risk_level="low",
        requires_confirmation=False,
        input_schema={"packs": {"type": "array"}},
    ),
    "attach_openviking_context_pack": ExecutiveActionDefinition(
        action_id="attach_openviking_context_pack",
        label="Attach Context Pack",
        description="Attach a context pack to the active Executive or workspace context.",
        component_scope=["openviking"],
        risk_level="low",
        requires_confirmation=False,
        input_schema={"pack_id": {"type": "string"}, "context_key": {"type": "string"}},
    ),
    "sync_activepieces_flows": ExecutiveActionDefinition(
        action_id="sync_activepieces_flows",
        label="Sync Approved Flows",
        description="Register one or more approved Activepieces flows.",
        component_scope=["activepieces"],
        risk_level="low",
        requires_confirmation=False,
        input_schema={"flows": {"type": "array"}},
    ),
    "trigger_activepieces_flow": ExecutiveActionDefinition(
        action_id="trigger_activepieces_flow",
        label="Trigger Flow",
        description="Trigger an approved Activepieces flow with the provided payload.",
        component_scope=["activepieces"],
        risk_level="high",
        requires_confirmation=True,
        input_schema={"flow_id": {"type": "string"}, "payload": {"type": "object"}},
    ),
    "select_browser_runtime": ExecutiveActionDefinition(
        action_id="select_browser_runtime",
        label="Select Browser Runtime",
        description="Resolve the preferred browser runtime and fallback behavior.",
        component_scope=["browser_runtime"],
        risk_level="low",
        requires_confirmation=False,
        input_schema={"prefer_lightpanda": {"type": "boolean"}, "allow_fallback": {"type": "boolean"}},
    ),
    "create_browser_job": ExecutiveActionDefinition(
        action_id="create_browser_job",
        label="Create Browser Job",
        description="Submit a browser-runtime job for execution.",
        component_scope=["browser_runtime"],
        risk_level="medium",
        requires_confirmation=False,
        input_schema={"job_type": {"type": "string"}, "payload": {"type": "object"}},
    ),
    "create_state_snapshot": ExecutiveActionDefinition(
        action_id="create_state_snapshot",
        label="Create State Snapshot",
        description="Persist a snapshot of executable state for comparison or audit.",
        component_scope=["stateweave"],
        risk_level="low",
        requires_confirmation=False,
        input_schema={"state_type": {"type": "string"}, "label": {"type": "string"}, "payload": {"type": "object"}},
    ),
    "diff_state_snapshots": ExecutiveActionDefinition(
        action_id="diff_state_snapshots",
        label="Diff State Snapshots",
        description="Compare two persisted snapshots and store the diff.",
        component_scope=["stateweave"],
        risk_level="low",
        requires_confirmation=False,
        input_schema={"from_snapshot_id": {"type": "string"}, "to_snapshot_id": {"type": "string"}},
    ),
    "export_state_snapshot": ExecutiveActionDefinition(
        action_id="export_state_snapshot",
        label="Export State Snapshot",
        description="Serialize a persisted snapshot for debugging or transport.",
        component_scope=["stateweave"],
        risk_level="low",
        requires_confirmation=False,
        input_schema={"snapshot_id": {"type": "string"}},
    ),
    "register_blueprint": ExecutiveActionDefinition(
        action_id="register_blueprint",
        label="Register Blueprint",
        description="Store an Executive blueprint definition.",
        component_scope=["executive"],
        risk_level="low",
        requires_confirmation=False,
        input_schema={"blueprint": {"type": "object"}},
    ),
    "record_heartbeat": ExecutiveActionDefinition(
        action_id="record_heartbeat",
        label="Record Heartbeat",
        description="Persist a heartbeat for a blueprint or long-running execution.",
        component_scope=["executive"],
        risk_level="low",
        requires_confirmation=False,
        input_schema={"scope_type": {"type": "string"}, "scope_id": {"type": "string"}},
    ),
    "restart_component": ExecutiveActionDefinition(
        action_id="restart_component",
        label="Restart Component",
        description="Restart a host-managed integration using its registered command path.",
        component_scope=["litellm", "langfuse", "surfsense"],
        risk_level="high",
        requires_confirmation=True,
    ),
    "start_component": ExecutiveActionDefinition(
        action_id="start_component",
        label="Start Component",
        description="Start a host-managed integration using its registered command path.",
        component_scope=["litellm", "langfuse", "surfsense"],
        risk_level="high",
        requires_confirmation=True,
    ),
    "stop_component": ExecutiveActionDefinition(
        action_id="stop_component",
        label="Stop Component",
        description="Stop a host-managed integration using its registered command path.",
        component_scope=["litellm", "langfuse", "surfsense"],
        risk_level="high",
        requires_confirmation=True,
    ),
}


COMPONENTS: dict[str, ExecutiveComponent] = {
    "frontend": ExecutiveComponent(
        component_id="frontend",
        label="Frontend",
        kind="service",
        owner="workspace",
        description="Next.js workspace UI served through nginx.",
        dependencies=["nginx", "gateway"],
        status_adapter="frontend",
        actions=["recheck_component", "collect_component_diagnostics", "tail_component_logs", "run_connectivity_check"],
        best_practices=["Use the dedicated Executive workspace for operations, not the general chat thread."],
    ),
    "gateway": ExecutiveComponent(
        component_id="gateway",
        label="Gateway",
        kind="service",
        owner="backend",
        description="FastAPI API surface for MaestroFlow custom endpoints.",
        dependencies=["langgraph"],
        status_adapter="gateway",
        actions=["recheck_component", "collect_component_diagnostics", "tail_component_logs", "run_connectivity_check"],
        best_practices=["Keep custom control-plane routes in the gateway so failures degrade cleanly."],
    ),
    "langgraph": ExecutiveComponent(
        component_id="langgraph",
        label="LangGraph",
        kind="service",
        owner="backend",
        description="LangGraph server for conversational agents and streaming threads.",
        dependencies=["litellm"],
        status_adapter="langgraph",
        actions=["recheck_component", "collect_component_diagnostics", "tail_component_logs", "run_connectivity_check"],
        best_practices=["Treat LangGraph availability as required for normal chat routing."],
        risk_level="high",
    ),
    "nginx": ExecutiveComponent(
        component_id="nginx",
        label="Nginx",
        kind="service",
        owner="infra",
        description="Reverse proxy in front of frontend, gateway, and LangGraph.",
        dependencies=["frontend", "gateway"],
        status_adapter="nginx",
        actions=["recheck_component", "collect_component_diagnostics", "tail_component_logs", "run_connectivity_check"],
        best_practices=["Keep all UI and API routes available through the single MaestroFlow entrypoint."],
    ),
    "lead_agent": ExecutiveComponent(
        component_id="lead_agent",
        label="Lead Agent",
        kind="agent",
        owner="agents",
        description="Primary conversational agent used by normal threads.",
        dependencies=["litellm", "langgraph"],
        status_adapter="lead_agent",
        actions=["recheck_component", "collect_component_diagnostics", "set_default_model"],
        best_practices=["Prefer the lead agent for general orchestration, not for privileged control actions."],
        managed_scope="configurable",
        requires_confirmation_for=["set_default_model"],
    ),
    "subagents": ExecutiveComponent(
        component_id="subagents",
        label="Subagents",
        kind="agent_system",
        owner="agents",
        description="Parallel delegated agents used in Ultra and specialized workflows.",
        dependencies=["lead_agent", "litellm"],
        status_adapter="subagents",
        actions=[
            "recheck_component",
            "collect_component_diagnostics",
            "update_subagent_timeout",
            "update_subagent_concurrency_policy",
        ],
        best_practices=[
            "Keep CLI-heavy or build-heavy subagents at lower concurrency than lightweight research agents.",
            "Use longer timeouts for long-running CLI work and shorter defaults for routine research work.",
        ],
        managed_scope="configurable",
        requires_confirmation_for=["update_subagent_timeout", "update_subagent_concurrency_policy"],
    ),
    "doc_editing": ExecutiveComponent(
        component_id="doc_editing",
        label="Doc Editing",
        kind="workflow",
        owner="editorial",
        description="Parallel doc-edit workflow with review and finalization.",
        dependencies=["litellm"],
        status_adapter="doc_editing",
        actions=["recheck_component", "collect_component_diagnostics", "cancel_doc_edit_run", "retry_doc_edit_run"],
        best_practices=["Use doc-edit when you want controlled multi-version editing, not a general chat rewrite."],
        managed_scope="configurable",
        requires_confirmation_for=["cancel_doc_edit_run", "retry_doc_edit_run"],
    ),
    "mcp": ExecutiveComponent(
        component_id="mcp",
        label="MCP",
        kind="integration_hub",
        owner="extensions",
        description="Configured MCP servers and their cached tool availability.",
        dependencies=["gateway"],
        status_adapter="mcp",
        actions=["recheck_component", "collect_component_diagnostics", "refresh_mcp", "enable_mcp_server", "disable_mcp_server"],
        best_practices=["Disable stale or broken MCP servers rather than leaving them half-configured."],
        managed_scope="configurable",
        requires_confirmation_for=["enable_mcp_server", "disable_mcp_server"],
    ),
    "autoresearch": ExecutiveComponent(
        component_id="autoresearch",
        label="Autoresearcher",
        kind="workflow",
        owner="optimization",
        description="Prompt and workflow optimization lab with Executive-gated promotion.",
        dependencies=["subagents", "langfuse"],
        status_adapter="autoresearch",
        actions=[
            "recheck_component",
            "collect_component_diagnostics",
            "approve_autoresearch_experiment",
            "reject_autoresearch_experiment",
            "rollback_autoresearch_prompt",
            "stop_autoresearch_experiment",
        ],
        best_practices=[
            "Keep experiments offline until their evals are stable.",
            "Promote winners only after reviewing benchmark scores and failure buckets.",
        ],
        managed_scope="configurable",
        requires_confirmation_for=[
            "approve_autoresearch_experiment",
            "reject_autoresearch_experiment",
            "rollback_autoresearch_prompt",
            "stop_autoresearch_experiment",
        ],
    ),
    "openviking": ExecutiveComponent(
        component_id="openviking",
        label="OpenViking",
        kind="integration",
        owner="context",
        description="Context pack registry and hydration sidecar.",
        dependencies=["gateway"],
        status_adapter="openviking",
        actions=["recheck_component", "collect_component_diagnostics", "sync_context_packs"],
        best_practices=["Treat context packs as additive context, not as a replacement for SurfSense or durable memory."],
        managed_scope="configurable",
    ),
    "activepieces": ExecutiveComponent(
        component_id="activepieces",
        label="Activepieces",
        kind="integration",
        owner="automation",
        description="Approved automation bridge and inbound webhook handler.",
        dependencies=["gateway"],
        status_adapter="activepieces",
        actions=["recheck_component", "collect_component_diagnostics", "run_approved_flow"],
        best_practices=["Run only approved flows through MaestroFlow so Executive can preserve audit and approval lineage."],
        managed_scope="configurable",
        requires_confirmation_for=["run_approved_flow"],
    ),
    "browser_runtime": ExecutiveComponent(
        component_id="browser_runtime",
        label="Browser Runtime",
        kind="integration",
        owner="automation",
        description="Playwright and Lightpanda browser job bridge.",
        dependencies=["gateway"],
        status_adapter="browser_runtime",
        actions=["recheck_component", "collect_component_diagnostics", "create_browser_job"],
        best_practices=["Prefer Playwright for compatibility-sensitive checks and Lightpanda for lightweight batch browsing."],
        managed_scope="configurable",
    ),
    "stateweave": ExecutiveComponent(
        component_id="stateweave",
        label="StateWeave",
        kind="integration",
        owner="observability",
        description="State snapshot and diff layer for experiments and workflows.",
        dependencies=["gateway"],
        status_adapter="stateweave",
        actions=["recheck_component", "collect_component_diagnostics", "create_state_snapshot"],
        best_practices=["Use state snapshots for reproducibility and diffing, not as the primary execution backend."],
        managed_scope="configurable",
    ),
    "channels": ExecutiveComponent(
        component_id="channels",
        label="Channels",
        kind="integration_hub",
        owner="channels",
        description="Configured IM channel connectors.",
        dependencies=["gateway", "langgraph"],
        status_adapter="channels",
        actions=["recheck_component", "collect_component_diagnostics", "restart_channel"],
        best_practices=["Restart one failing channel first; do not bounce the whole system for a single connector issue."],
        managed_scope="configurable",
        requires_confirmation_for=["restart_channel"],
    ),
    "litellm": ExecutiveComponent(
        component_id="litellm",
        label="LiteLLM",
        kind="integration",
        owner="models",
        description="Unified model gateway for local and remote model routing.",
        dependencies=[],
        status_adapter="litellm",
        actions=["recheck_component", "collect_component_diagnostics", "tail_component_logs", "run_connectivity_check", "start_component", "stop_component", "restart_component"],
        best_practices=["Keep LiteLLM healthy before debugging higher-level chat failures."],
        risk_level="critical",
        managed_scope="host_managed",
        requires_confirmation_for=["start_component", "stop_component", "restart_component"],
    ),
    "langfuse": ExecutiveComponent(
        component_id="langfuse",
        label="Langfuse",
        kind="integration",
        owner="observability",
        description="Tracing and evaluation sink for MaestroFlow runs.",
        dependencies=[],
        status_adapter="langfuse",
        actions=["recheck_component", "collect_component_diagnostics", "tail_component_logs", "run_connectivity_check", "start_component", "stop_component", "restart_component"],
        best_practices=["Treat Langfuse as optional for runtime correctness but important for diagnosis and evals."],
        managed_scope="host_managed",
        requires_confirmation_for=["start_component", "stop_component", "restart_component"],
    ),
    "surfsense": ExecutiveComponent(
        component_id="surfsense",
        label="SurfSense",
        kind="integration",
        owner="knowledge",
        description="Knowledge substrate and research handoff integration.",
        dependencies=[],
        status_adapter="surfsense",
        actions=["recheck_component", "collect_component_diagnostics", "tail_component_logs", "run_connectivity_check", "start_component", "stop_component", "restart_component"],
        best_practices=["Use SurfSense first for known internal knowledge, then fall back to broader research."],
        managed_scope="host_managed",
        requires_confirmation_for=["start_component", "stop_component", "restart_component"],
    ),
    "openviking": ExecutiveComponent(
        component_id="openviking",
        label="OpenViking",
        kind="integration",
        owner="knowledge",
        description="Context pack registry for reusable research and orchestration context.",
        dependencies=[],
        status_adapter="openviking",
        actions=["recheck_component", "collect_component_diagnostics", "sync_openviking_context_packs", "attach_openviking_context_pack"],
        best_practices=["Keep reusable context packs versioned and attach only the minimum necessary pack set."],
        managed_scope="configurable",
    ),
    "activepieces": ExecutiveComponent(
        component_id="activepieces",
        label="Activepieces",
        kind="integration",
        owner="automation",
        description="Approved-flow automation bridge for external workflows and webhooks.",
        dependencies=[],
        status_adapter="activepieces",
        actions=["recheck_component", "collect_component_diagnostics", "sync_activepieces_flows", "trigger_activepieces_flow"],
        best_practices=["Approve automation flows explicitly before routing live user work through them."],
        managed_scope="configurable",
        requires_confirmation_for=["trigger_activepieces_flow"],
    ),
    "browser_runtime": ExecutiveComponent(
        component_id="browser_runtime",
        label="Browser Runtime",
        kind="integration",
        owner="automation",
        description="Browser runtime selection and job execution abstraction for Playwright and Lightpanda.",
        dependencies=[],
        status_adapter="browser_runtime",
        actions=["recheck_component", "collect_component_diagnostics", "select_browser_runtime", "create_browser_job"],
        best_practices=["Use Playwright for compatibility-sensitive flows and Lightpanda for batch browsing when available."],
        managed_scope="configurable",
    ),
    "stateweave": ExecutiveComponent(
        component_id="stateweave",
        label="StateWeave",
        kind="integration",
        owner="observability",
        description="State snapshot, diff, and export layer for experiments and workflow routes.",
        dependencies=[],
        status_adapter="stateweave",
        actions=["recheck_component", "collect_component_diagnostics", "create_state_snapshot", "diff_state_snapshots", "export_state_snapshot"],
        best_practices=["Take snapshots before mutating workflows so diffs remain understandable."],
        managed_scope="observe_only",
    ),
    "executive": ExecutiveComponent(
        component_id="executive",
        label="Executive",
        kind="control_plane",
        owner="system",
        description="MaestroFlow control plane for blueprints, heartbeats, and operator tasks.",
        dependencies=["gateway"],
        status_adapter="executive",
        actions=["recheck_component", "collect_component_diagnostics", "register_blueprint", "record_heartbeat"],
        best_practices=["Treat blueprints and heartbeats as the control-plane audit trail for long-running jobs."],
        managed_scope="configurable",
    ),
}


def get_component_registry() -> dict[str, ExecutiveComponent]:
    return COMPONENTS


def list_action_definitions() -> list[ExecutiveActionDefinition]:
    return list(ACTION_DEFINITIONS.values())
