from __future__ import annotations

from src.executive.models import ExecutiveActionDefinition, ExecutiveComponent


ACTION_DEFINITIONS: dict[str, ExecutiveActionDefinition] = {
    "recheck_component": ExecutiveActionDefinition(
        action_id="recheck_component",
        label="Recheck Component",
        description="Refresh live health information for one component.",
        component_scope=["*"],
        risk_level="low",
        requires_confirmation=False,
    ),
    "collect_component_diagnostics": ExecutiveActionDefinition(
        action_id="collect_component_diagnostics",
        label="Collect Diagnostics",
        description="Gather a structured diagnostic snapshot for a component.",
        component_scope=["*"],
        risk_level="low",
        requires_confirmation=False,
    ),
    "tail_component_logs": ExecutiveActionDefinition(
        action_id="tail_component_logs",
        label="Tail Logs",
        description="Read the latest relevant lines for a component log.",
        component_scope=["frontend", "gateway", "langgraph", "nginx", "litellm", "langfuse", "surfsense"],
        risk_level="low",
        requires_confirmation=False,
        input_schema={"lines": {"type": "integer", "minimum": 10, "maximum": 200}},
    ),
    "run_connectivity_check": ExecutiveActionDefinition(
        action_id="run_connectivity_check",
        label="Run Connectivity Check",
        description="Perform a direct connectivity probe against a component endpoint.",
        component_scope=["frontend", "gateway", "langgraph", "nginx", "litellm", "langfuse", "surfsense"],
        risk_level="low",
        requires_confirmation=False,
    ),
    "refresh_mcp": ExecutiveActionDefinition(
        action_id="refresh_mcp",
        label="Refresh MCP",
        description="Reload extensions config and reset the MCP tool cache.",
        component_scope=["mcp"],
        risk_level="low",
        requires_confirmation=False,
    ),
    "enable_mcp_server": ExecutiveActionDefinition(
        action_id="enable_mcp_server",
        label="Enable MCP Server",
        description="Enable a configured MCP server in extensions config.",
        component_scope=["mcp"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"server_name": {"type": "string"}},
    ),
    "disable_mcp_server": ExecutiveActionDefinition(
        action_id="disable_mcp_server",
        label="Disable MCP Server",
        description="Disable a configured MCP server in extensions config.",
        component_scope=["mcp"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"server_name": {"type": "string"}},
    ),
    "restart_channel": ExecutiveActionDefinition(
        action_id="restart_channel",
        label="Restart Channel",
        description="Restart one configured IM channel.",
        component_scope=["channels"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"channel_name": {"type": "string"}},
    ),
    "update_subagent_timeout": ExecutiveActionDefinition(
        action_id="update_subagent_timeout",
        label="Update Subagent Timeout",
        description="Apply a runtime timeout override for subagents.",
        component_scope=["subagents"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={
            "timeout_seconds": {"type": "integer", "minimum": 60, "maximum": 7200},
            "agent_name": {"type": "string"},
        },
    ),
    "update_subagent_concurrency_policy": ExecutiveActionDefinition(
        action_id="update_subagent_concurrency_policy",
        label="Update Subagent Concurrency",
        description="Apply a runtime concurrency override for the lead agent's subagent fan-out.",
        component_scope=["subagents"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"max_concurrent_subagents": {"type": "integer", "minimum": 1, "maximum": 4}},
    ),
    "set_default_model": ExecutiveActionDefinition(
        action_id="set_default_model",
        label="Set Default Model",
        description="Apply a runtime default model override for MaestroFlow agents.",
        component_scope=["lead_agent"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"model_name": {"type": "string"}},
    ),
    "cancel_doc_edit_run": ExecutiveActionDefinition(
        action_id="cancel_doc_edit_run",
        label="Cancel Doc Edit Run",
        description="Mark an awaiting-selection doc edit run as cancelled.",
        component_scope=["doc_editing"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"run_id": {"type": "string"}},
    ),
    "retry_doc_edit_run": ExecutiveActionDefinition(
        action_id="retry_doc_edit_run",
        label="Retry Doc Edit Run",
        description="Create a fresh doc edit run from a previous run's manifest.",
        component_scope=["doc_editing"],
        risk_level="medium",
        requires_confirmation=True,
        input_schema={"run_id": {"type": "string"}},
    ),
    "restart_component": ExecutiveActionDefinition(
        action_id="restart_component",
        label="Restart Component",
        description="Restart a host-managed integration using its registered command path.",
        component_scope=["litellm", "langfuse", "surfsense"],
        risk_level="high",
        requires_confirmation=True,
    ),
    "start_component": ExecutiveActionDefinition(
        action_id="start_component",
        label="Start Component",
        description="Start a host-managed integration using its registered command path.",
        component_scope=["litellm", "langfuse", "surfsense"],
        risk_level="high",
        requires_confirmation=True,
    ),
    "stop_component": ExecutiveActionDefinition(
        action_id="stop_component",
        label="Stop Component",
        description="Stop a host-managed integration using its registered command path.",
        component_scope=["litellm", "langfuse", "surfsense"],
        risk_level="high",
        requires_confirmation=True,
    ),
}


COMPONENTS: dict[str, ExecutiveComponent] = {
    "frontend": ExecutiveComponent(
        component_id="frontend",
        label="Frontend",
        kind="service",
        owner="workspace",
        description="Next.js workspace UI served through nginx.",
        dependencies=["nginx", "gateway"],
        status_adapter="frontend",
        actions=["recheck_component", "collect_component_diagnostics", "tail_component_logs", "run_connectivity_check"],
        best_practices=["Use the dedicated Executive workspace for operations, not the general chat thread."],
    ),
    "gateway": ExecutiveComponent(
        component_id="gateway",
        label="Gateway",
        kind="service",
        owner="backend",
        description="FastAPI API surface for MaestroFlow custom endpoints.",
        dependencies=["langgraph"],
        status_adapter="gateway",
        actions=["recheck_component", "collect_component_diagnostics", "tail_component_logs", "run_connectivity_check"],
        best_practices=["Keep custom control-plane routes in the gateway so failures degrade cleanly."],
    ),
    "langgraph": ExecutiveComponent(
        component_id="langgraph",
        label="LangGraph",
        kind="service",
        owner="backend",
        description="LangGraph server for conversational agents and streaming threads.",
        dependencies=["litellm"],
        status_adapter="langgraph",
        actions=["recheck_component", "collect_component_diagnostics", "tail_component_logs", "run_connectivity_check"],
        best_practices=["Treat LangGraph availability as required for normal chat routing."],
        risk_level="high",
    ),
    "nginx": ExecutiveComponent(
        component_id="nginx",
        label="Nginx",
        kind="service",
        owner="infra",
        description="Reverse proxy in front of frontend, gateway, and LangGraph.",
        dependencies=["frontend", "gateway"],
        status_adapter="nginx",
        actions=["recheck_component", "collect_component_diagnostics", "tail_component_logs", "run_connectivity_check"],
        best_practices=["Keep all UI and API routes available through the single MaestroFlow entrypoint."],
    ),
    "lead_agent": ExecutiveComponent(
        component_id="lead_agent",
        label="Lead Agent",
        kind="agent",
        owner="agents",
        description="Primary conversational agent used by normal threads.",
        dependencies=["litellm", "langgraph"],
        status_adapter="lead_agent",
        actions=["recheck_component", "collect_component_diagnostics", "set_default_model"],
        best_practices=["Prefer the lead agent for general orchestration, not for privileged control actions."],
        managed_scope="configurable",
        requires_confirmation_for=["set_default_model"],
    ),
    "subagents": ExecutiveComponent(
        component_id="subagents",
        label="Subagents",
        kind="agent_system",
        owner="agents",
        description="Parallel delegated agents used in Ultra and specialized workflows.",
        dependencies=["lead_agent", "litellm"],
        status_adapter="subagents",
        actions=[
            "recheck_component",
            "collect_component_diagnostics",
            "update_subagent_timeout",
            "update_subagent_concurrency_policy",
        ],
        best_practices=[
            "Keep CLI-heavy or build-heavy subagents at lower concurrency than lightweight research agents.",
            "Use longer timeouts for long-running CLI work and shorter defaults for routine research work.",
        ],
        managed_scope="configurable",
        requires_confirmation_for=["update_subagent_timeout", "update_subagent_concurrency_policy"],
    ),
    "doc_editing": ExecutiveComponent(
        component_id="doc_editing",
        label="Doc Editing",
        kind="workflow",
        owner="editorial",
        description="Parallel doc-edit workflow with review and finalization.",
        dependencies=["litellm"],
        status_adapter="doc_editing",
        actions=["recheck_component", "collect_component_diagnostics", "cancel_doc_edit_run", "retry_doc_edit_run"],
        best_practices=["Use doc-edit when you want controlled multi-version editing, not a general chat rewrite."],
        managed_scope="configurable",
        requires_confirmation_for=["cancel_doc_edit_run", "retry_doc_edit_run"],
    ),
    "mcp": ExecutiveComponent(
        component_id="mcp",
        label="MCP",
        kind="integration_hub",
        owner="extensions",
        description="Configured MCP servers and their cached tool availability.",
        dependencies=["gateway"],
        status_adapter="mcp",
        actions=["recheck_component", "collect_component_diagnostics", "refresh_mcp", "enable_mcp_server", "disable_mcp_server"],
        best_practices=["Disable stale or broken MCP servers rather than leaving them half-configured."],
        managed_scope="configurable",
        requires_confirmation_for=["enable_mcp_server", "disable_mcp_server"],
    ),
    "channels": ExecutiveComponent(
        component_id="channels",
        label="Channels",
        kind="integration_hub",
        owner="channels",
        description="Configured IM channel connectors.",
        dependencies=["gateway", "langgraph"],
        status_adapter="channels",
        actions=["recheck_component", "collect_component_diagnostics", "restart_channel"],
        best_practices=["Restart one failing channel first; do not bounce the whole system for a single connector issue."],
        managed_scope="configurable",
        requires_confirmation_for=["restart_channel"],
    ),
    "litellm": ExecutiveComponent(
        component_id="litellm",
        label="LiteLLM",
        kind="integration",
        owner="models",
        description="Unified model gateway for local and remote model routing.",
        dependencies=[],
        status_adapter="litellm",
        actions=["recheck_component", "collect_component_diagnostics", "tail_component_logs", "run_connectivity_check", "start_component", "stop_component", "restart_component"],
        best_practices=["Keep LiteLLM healthy before debugging higher-level chat failures."],
        risk_level="critical",
        managed_scope="host_managed",
        requires_confirmation_for=["start_component", "stop_component", "restart_component"],
    ),
    "langfuse": ExecutiveComponent(
        component_id="langfuse",
        label="Langfuse",
        kind="integration",
        owner="observability",
        description="Tracing and evaluation sink for MaestroFlow runs.",
        dependencies=[],
        status_adapter="langfuse",
        actions=["recheck_component", "collect_component_diagnostics", "tail_component_logs", "run_connectivity_check", "start_component", "stop_component", "restart_component"],
        best_practices=["Treat Langfuse as optional for runtime correctness but important for diagnosis and evals."],
        managed_scope="host_managed",
        requires_confirmation_for=["start_component", "stop_component", "restart_component"],
    ),
    "surfsense": ExecutiveComponent(
        component_id="surfsense",
        label="SurfSense",
        kind="integration",
        owner="knowledge",
        description="Knowledge substrate and research handoff integration.",
        dependencies=[],
        status_adapter="surfsense",
        actions=["recheck_component", "collect_component_diagnostics", "tail_component_logs", "run_connectivity_check", "start_component", "stop_component", "restart_component"],
        best_practices=["Use SurfSense first for known internal knowledge, then fall back to broader research."],
        managed_scope="host_managed",
        requires_confirmation_for=["start_component", "stop_component", "restart_component"],
    ),
}


def get_component_registry() -> dict[str, ExecutiveComponent]:
    return COMPONENTS


def list_action_definitions() -> list[ExecutiveActionDefinition]:
    return list(ACTION_DEFINITIONS.values())
